### ISSUE TITLE
Role authorization scoping for 2.0

### ISSUE THREAD

**Issue by prairir** [uwindsorcss/css-discord-bot#47]
#### Describe Problem
There is no current authorization scoping in 2.0

This means that anyone can run any command
#### Suggest Changes
Add different scopes with different levels of privledges

**Comment by prairir** [comment]
This would be an advanced issues scoping. As command permissions cannot be revoked, the **minimum** role that can use this command is required.

The config for role permissions would look like
```yaml
command_permissions:
    <command name>:  "<role name>"
```

example:
```yaml
command_permissions:
    whereis:  "everyone"
    ping: "pong"
```

In this example, everyone can use `whereis` but only people with the role `pong` can use the `ping` command.

This would be done for every command

**Comment by prairir** [comment]
This is taken directly from Isaacs branch

```
global_features:
  - pong


guilds:
  "your_guild_id_here":
    name: "your amazing server"
    features:
      - purge
    role_perms:
      "Admin":
        - purge
```

so this works in 2 parts. Global features and guild features. 

Global features are enabled on **all** servers for **everyone**. 
Guild features are enabled on the **specific** server for the **specific** role.

under the guilds section, you have `features` and `role_perms`

`features` is what features are enabled.
`role_perms` are what features can be used at that role or above. 
for example, if I have 2 roles called `admin` and `guest`. `admin` is above `guest`. We want to have a `purge` command that only admin can use and a `map` command that everyone can use no matter the role.

```
global_features:
  - map


guilds:
  "123455":
    name: "example server"
    features:
      - purge
    role_perms:
      "admin":
        - purge
```

since `admin` is above `guest` and `admin` has `purge` both enabled and perm set, it will work for only `admin`.

lets say we have a security issue in `purge`, we would want to disable it without removing the role perm config. That is easy, you would just do 
```
global_features:
  - map


guilds:
  "123455":
    name: "example server"
    features: []
    role_perms:
      "admin":
        - purge
```
